spring:
  application:
    name: bookstore
  webflux:
    base-path: /api
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/bookstore
    username: root
    password: my-secret-pw
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none

bookstore:
  limit-per-page: 25

logging:
  level:
    org:
      springframework:
        web:
          TRACE
