spring:
  application:
    name: bookstore
  webflux:
    base-path: /api
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/bookstore
    username: root
    password: my-secret-pw
  jpa:
    hibernate:
      ddl-auto: update

bookstore:
  limit-per-page: 25

logging:
  level:
    org:
      springframework:
        web:
          TRACE
