version: '3.9'

services:

  mysql5:
    image: mysql:8.0.23
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max_connections=600
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
      - ./mysql/01_bookstore_schema.sql:/docker-entrypoint-initdb.d/01_bookstore_schema.sql
      - ./mysql/02_bookstore_data.sql:/docker-entrypoint-initdb.d/02_bookstore_data.sql
    ports:
      - "3306:3306"
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    healthcheck:
      test: mysql --user=root --password=my-secret-pw --execute "SHOW DATABASES;"
      interval: 3s
      timeout: 1s
      retries: 20
    stop_grace_period: 30s
